### ISSUE TITLE
Create the docker image without the windows files

### ISSUE THREAD

**Issue by emilorol** [aerokube/windows-images#15]
I understand that reasoning of not providing a docker image with the windows files, but can you provide a docker image where the windows files have to be mounted?

By having a "windowless" docker image the user will still be responsible of providing the licenses, am I wrong or is this an slippery slop that can get you into trouble?

**Comment by vania-pooh** [comment]
@emilorol we are not sure whether we can push a copy of Windows to Docker Hub according to license terms.

**Comment by emilorol** [comment]
@vania-pooh I don't mean to push a copy of windows, but an "empty" container expecting the windows image file to be mapped to a volume path and run it from there.

I did an attempt myself here: https://hub.docker.com/r/emilorol/vnc_qemu

That image is expecting the windows image to be mounted to `/images/` directory in order to run. I updated the `entrypoint.sh` script to support this.

**Comment by vania-pooh** [comment]
Summon @aandryashin

**Comment by aandryashin** [comment]
Such  image will only contain entrypoint.sh... anyway we will think aboit
such approach...

пт, 20 сент. 2019 г., 8:31 Ivan Krutov <notifications@github.com>:

**Comment by emilorol** [comment]
The main reasoning is that right after you finish figthing Windows VM to have it as you need it, you then need to build a new docker image and put it somewhere. If there is already an image build that will consume your Windows VM that will be make life a lot better.

**Comment by aandryashin** [comment]
Actually if you mount snapshot as volume lt will be persistent and you will
not able back to initial state.

пт, 20 сент. 2019 г., 16:40 Emil Orol <notifications@github.com>:

**Comment by emilorol** [comment]
I am not sure if I understand what you are saying, but is it to have the windows snapshot as part of the docker image as sharing it (windows snapshot) with other containers will not work.

Did I get it right?

**Comment by aandryashin** [comment]
Yes, snapshot part of image is mutable and should be isolated from others
and should be packed to container. The only thing that can be shared is
snapshot's backend image... But snapshot is individual for it's backend
image. That is why we cannot build image without any part of windows. But
you can build your own image without hdd.img and mount it from filesystem...

пт, 20 сент. 2019 г., 19:13 Emil Orol <notifications@github.com>:

**Comment by emilorol** [comment]
Ok, thank you for the clarification. Keep up the good work.

Related: https://github.com/aerokube/moon/issues/158
