### ISSUE TITLE
Run virtual machine and install

### ISSUE THREAD

**Issue by szakika10** [aerokube/windows-images#18]
Hi, when i run this:

sudo qemu-system-x86_64 -enable-kvm \
        -machine q35 -smp sockets=1,cores=1,threads=2 -m 2048 \
        -usb -device usb-kbd -device usb-tablet -rtc base=localtime \
        -net nic,model=virtio -net user,hostfwd=tcp::4444-:4444 \
        -drive file=hdd.img,media=disk,if=virtio \
        -drive file=Win10_1809Oct_English_x32.iso,media=cdrom \
        -drive file=virtio-win-0.1.141.iso,media=cdrom 

i get this response:
qemu-system-x86_64: -net user,hostfwd=tcp::4444-:4444: Could not set up host forwarding rule 'tcp::4444-:4444'

Why ? What's the problem?

**Comment by vania-pooh** [comment]
@szakika10 couldn't you have a Selenium server already listening on port 4444? If you have Selenium server, Selenoid or Selenium Grid just stop it.

**Comment by szakika10** [comment]
Thx, something was listening on this port.

**Comment by vania-pooh** [comment]
@szakika10 closing then?

**Comment by szakika10** [comment]
Of course
