### ISSUE TITLE
multiple requests

### ISSUE THREAD

**Issue by szakika10** [aerokube/windows-images#20]
Hi,

I tried that, run 2 selenium test and, first was ok, but the second test get error. (I have a jar and I ran this 2 times at the same time. One of them from one terminal, and the other from other terminal)
is it possible somehow that works good? So the driver/url can serve two or more connection? if is it possible, then how?
Thanks and sorry for my english.. :) I hope i was clear

**Comment by aandryashin** [comment]
Actually, edge does not support parallel sessions, that is why we have to
pack it to docker image. Try to run separate docker container for every
test.

вт, 15 окт. 2019 г., 9:41 szakika10 <notifications@github.com>:

**Comment by szakika10** [comment]
thank you :)
