### ISSUE TITLE
failed to pull image "windows/ie:11"

### ISSUE THREAD

**Issue by taren7** [aerokube/windows-images#29]
Thanks for the detailed instructions on building the IE container. I was able to build the container image and 
It works also as described when running the container like this:
$ docker run -it --rm --privileged -p 4444:4444 -p 5900:5900 windows/ie:11

Then copied the image to another machine which is hosteing the selenoid server. 
The windows IE image was loaded properly.
When i try to run the selenoid server againgt the IE image, it gives an error
failed to pull image "windows/ie:11"

This is how the  browser.json is configured 

 
![image](https://user-images.githubusercontent.com/12555607/74930554-ed3c2b80-5403-11ea-969f-0c9928c13fe2.png)

Do i need to create a private docker registory to pull the image ? Is it possible to point it to loaded docker images ?

**Comment by vania-pooh** [comment]
@taren7 just take a look at `docker images  | grep windows` to see whether you have this image on your host. Selenoid does not pull images automatically.

**Comment by taren7** [comment]
@vania-pooh  the image is available and loaded on the host
![image](https://user-images.githubusercontent.com/12555607/74932053-f24eaa00-5406-11ea-835e-35052be553a6.png)

**Comment by aandryashin** [comment]
Selenoid does not try to pull image, are you sure that error "failed to
pull image" comes from selenoid? If image is present on host, selenoid
should use it, could you please double check it?

чт, 20 февр. 2020 г., 15:02 taren7 <notifications@github.com>:

**Comment by taren7** [comment]
@aandryashin 
I am using cm to start selenoid server using custom browser.json. This is the output from the command :
![image](https://user-images.githubusercontent.com/12555607/74938426-fdf49d80-5413-11ea-932b-af4d2dad0d28.png)

the image is present on host but seems like the cm start command is looking for a valid repository for the ie docker image. Is there another way to double check this? Could i retrive any logs to help debug the issue ?

**Comment by aandryashin** [comment]
Cm trying to pull image, not selenoid itself. You can start selenoid using
docker and everything should just work, please refer to this doc section:

https://aerokube.com/selenoid/latest/#_starting_selenoid_manually

Please create github issue on cm repository and we will fix it in further
releases.

чт, 20 февр. 2020 г., 16:38 taren7 <notifications@github.com>:

**Comment by vania-pooh** [comment]
@taren7 CM always tries to pull images you specify in `browsers.json`. So I would first generate some `browsers.json` with CM, then add your image to it, then restart Selenoid container.

**Comment by taren7** [comment]
@aandryashin @vania-pooh Thanks for your support. I started the selenoid server manually and it worked.
