### ISSUE TITLE
 "wait: http://172.17.0.4:4444/ does not respond in 30s"

### ISSUE THREAD

**Issue by taren7** [aerokube/windows-images#30]
When I try to run Test case on IE , I get the error:
 "wait: http://172.17.0.4:4444/ does not respond in 30s"
The test case is working fine for chrome and Firefox.
On running the image without solenoid, I can do a vnc and checked that selenium web driver is configured fine and is in running state.
![image](https://user-images.githubusercontent.com/12555607/75031089-7ec2a080-54cb-11ea-95a6-041820e4ee05.png)
 

The browser.json has following tags for IE:
 
![image](https://user-images.githubusercontent.com/12555607/75031098-83875480-54cb-11ea-9c21-e223e75573cb.png)

After running the test on this docker instance (without selenoid) , it gives following error :
"Unexpected error. System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 10.220.51.54:4444\r\n   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)

I used following command to run the container without selenoid
_sudo docker run -it -d --rm --privileged -p 4442:4444 -p 5902:5900 --privileged windows/ie:11_

and then tried starting the browser through this :
_curl -X POST http://127.0.0.1:4442/session -d '{"capabilities": {"browserName": "internet explorer", "platform": "win10"}}'_

The response is : “curl: (52)Empty reply from server”
The firewall is disables and the port is also added to the incoming rules.
I have read the following posts : 
https://github.com/aerokube/windows-images/issues/21
https://github.com/aerokube/windows-images/issues/24
These are the docker logs :
 
![image](https://user-images.githubusercontent.com/12555607/75031152-9d289c00-54cb-11ea-9b89-226bc7892699.png)

Is there anything else I can try to check this.

**Comment by vania-pooh** [comment]
@taren7 you can try to increase timeout with `-service-startup-timeout 1m` flag.

**Comment by taren7** [comment]
The isuue is now resolved. The Initial problem was due to firewall setting on the image. It did not allow traffic on port 4444. 
After that I changed the startup timeout to 2m using the command  -service-startup-timeout 2m.
