### ISSUE TITLE
Question - Image

### ISSUE THREAD

**Issue by ilanisme** [aerokube/windows-images#32]
Hey,
i'm trying to understand, the final result is a docker image that has a vm with windows 10 ? or is the image only windows 10 with the browser?
Also, if the docker image does not contain a vm inside, can you do the same with windows 7 ? basically dockerize an older versions of internet explorer ?
Thanks in advance!

**Comment by vania-pooh** [comment]
@ilanisme this image always contains a VM inside, so you can dockerize any Windows version you want.

**Comment by ilanisme** [comment]
I see, isn't that a performance issue to have a vm inside of a container ? whats the advantage of docker then ?
thank you.

**Comment by vania-pooh** [comment]
@ilanisme you can't run Windows inside Docker directly, but you can run a Windows VM using Linux commands inside. So there is no choice.

**Comment by taren7** [comment]
@vania-pooh can we use a windows base image [Container Base Images](https://docs.microsoft.com/en-us/virtualization/windowscontainers/manage-containers/container-base-images)

**Comment by aandryashin** [comment]
No, it is not possible to run graphical applications in windows based
containers.

вт, 24 мар. 2020 г., 11:05 taren7 <notifications@github.com>:
