### ISSUE TITLE
Possible to build image so that it runs on windows VM

### ISSUE THREAD

**Issue by bs1** [aerokube/windows-images#35]
Is it possible to build the windows image so that it can run on a windows VM? or if not, runnable in some way that doesn't require nested virtualization. Maybe this is similar in spirit to https://github.com/aerokube/windows-images/issues/5

**Comment by vania-pooh** [comment]
@bs1 you can run iedriver with Selenoid on a standard Windows VM as described here: https://medium.com/@aandryashin/selenium-on-windows-revisited-1ab8d51ccc06

**Comment by bs1** [comment]
Thanks, is there a way to bundle those components into an image? something like https://github.com/aerokube/windows-images/blob/master/image/Dockerfile but on top of https://hub.docker.com/_/microsoft-windows-base-os-images

**Comment by vania-pooh** [comment]
@bs1 nope, because Windows base images support only command-line applications like IIS.

**Comment by bs1** [comment]
thanks for the info
