### ISSUE TITLE
Unable to connect VNC 

### ISSUE THREAD

**Issue by seasoncool** [aerokube/windows-images#4]
Hi,
Thanks for your tutorial, i can setup the container right now.
However, i'm unable to connect vnc from vnc viewer, i have print out the log of container, it says:

 --- x11vnc loop: 666 ---
 --- x11vnc loop: waiting for: 700
 --- x11vnc loop: sleeping 500 ms ---

![image](https://user-images.githubusercontent.com/6467295/60349526-580fa100-99f4-11e9-9bce-31da2b166e24.png)

Could your please share with me workaround about this issue? thanks  so much.

**Comment by aandryashin** [comment]
It looks like qemu cannot start, there should be any errors about it.
Please try to run qemu with image manually, using command from
everything.sh.

пт, 28 июня 2019 г., 17:29 James <notifications@github.com>:

**Comment by vania-pooh** [comment]
@seasoncool I think there is a typo in Alexander comment (should be `entrypoint.sh`).

**Comment by seasoncool** [comment]
Thanks @aandryashin  and @vania-pooh .

I have reinstalled the container from another ubuntu PC,  problem solved now.
