### ISSUE TITLE
Is windows os chrome really different from linux？

### ISSUE THREAD

**Issue by izachwei** [aerokube/windows-images#44]
Hi ,
I have a question. Does installing vm in docker container, Virtual windows system really bring value?Is there really a difference between linux and windows chrome

I hope you can answer that. Thank you very much

**Comment by vania-pooh** [comment]
@izachwei we consider that it does not bring value. Probably only fonts differ. This solution was mainly needed for running Internet Explorer in containers.

**Comment by izachwei** [comment]
> @izachwei we consider that it does not bring value. Probably only fonts differ. This solution was mainly needed for running Internet Explorer in containers.

thanks.
