### ISSUE TITLE
Windows 10 Pro 64 bit

### ISSUE THREAD

**Issue by stansa** [aerokube/windows-images#6]
Hello,

Very helpful instructions. 

I was able to get it working on Windows 10 Pro 32 bit only. Is that a restriction?

Have you tested with Windows 10 64 bit images and drivers? 

It might have something to do with the virtio-win-0.1.141.iso driver not being available for Windows 10 64bit.

Thanks!

**Comment by aandryashin** [comment]
64 bit image is two times bigger and very unstable running under qemu, we
decided to build only 32 bit yet...

ср, 10 июл. 2019 г., 20:24 Stan S <notifications@github.com>:

**Comment by stansa** [comment]
Thank you. 

Along the same lines of performance. Do the qemu startup options in your notes reflect any performance testing/tuning? I'm looking at this for example:
https://www.linux-kvm.org/page/Tuning_KVM

If you can point me to any other performance/tuning related docs would be much appreciated.

Thanks!
